[package]
name = "ernisto/simulator-brabo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
RandomOption = "ernisto/random-option@0.2.1"
Promise = "lukadev-0/typed-promise@4.0.2"
Rewire = "kennyjeopardy/rewire@0.3.1"
Fusion = "elttob/fusion@0.3.0-dev.1"
Spring = "mastrickdev/spring@0.2.4"
Ray = "ernisto/ray@0.1.2"

[server-dependencies]
ProfileService = "surnautica/profileservice@1.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"

[place]
shared-packages = "game.ReplicatedStorage.Packages"